# Generated by Django 4.1.7 on 2023-12-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('encrypted_text', models.TextField()),
                ('decrypted_text', models.TextField()),
            ],
        ),
    ]
